### PR TITLE
QuickFix "Press ENTER or ..." on Close

### PR DESCRIPTION
**Pull request by NemesisRE**

### CODE REVIEW

**Comment by xaizek** [comment]
What does the message say and what is the output of `set shortmess`? I'm asking because I don't see any messages even for very small window of Vim and wondering to which buffer that message is related.

**Comment by NemesisRE** [comment]
I mapped "Extradite!" to F6 when I press it with a running extradite buffer it will delete the buffers, I use cmdheight=1 and shortmess=aTI this is why I get the following message:

```
1 buffer deleted
1 buffer deleted
Press ENTER or type command to continue
```

**Comment by xaizek** [comment]
Still can't test it (found the message in sources of Vim, which led me to `'report'` option, but there must be something more that blocks it for me), but will merge. Thanks!

**Comment by NemesisRE** [comment]
Thank you :)

**Pull request merged**
